
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

    target-branch: "develop"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
