language: java

jdk:
  - oraclejdk11
  - openjdk11

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
  - unzip -qq apache-maven-3.6.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

install: true

script:
  - mvn --errors clean verify site
  - bash <(curl -s https://codecov.io/bash) -f ./com.io7m.jspatial.tests/target/site/jacoco-aggregate/jacoco.xml

notifications:
  irc: "chat.freenode.net#io7m"

