
name: main.linux.temurin.lts

on:
  push:
    branches: [ develop, feature/*, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Collect project version
        id: project_version
        run: java .github/workflows/Tools.java ShowProjectVersion pom.xml >> "$GITHUB_OUTPUT"

      - name: Collect project snapshot
        id: project_is_snapshot
        run: java .github/workflows/Tools.java ShowProjectIsSnapshot pom.xml >> "$GITHUB_OUTPUT"

      - name: Build
        run: mvn --batch-mode --strict-checksums --errors clean verify site

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-logs
          path: ./com.io7m.jspatial.tests/target/surefire-reports

      - name: Coverage
        uses: codecov/codecov-action@v4.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: com.io7m.jspatial.tests/target/site/jacoco-aggregate/jacoco.xml

      - name: Deploy snapshot
        if: ${{ steps.project_is_snapshot.outputs.IO7M_PROJECT_VERSION_IS_SNAPSHOT == 'true' }}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: .github/workflows/deploy-snapshot.sh

